name: Jammy

on:
  push: 
    branches: [ main ]
    paths:
      - 'scripts/**'
      - '.github/workflows/**'
  workflow_dispatch:

concurrency: 
  group: ubuntu-iso-build
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        descriptor: ["jammy-minimal"]
        include:
          - descriptor: "jammy-minimal"
            config-file: jammy-minimal.sh

    steps:
      - uses: actions/checkout@v3
      
      - name: Clean Up
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          echo "::group::Disk Space After Cleanup"
          df -hlT /
      
      - name: Build ISO
        id: build-iso
        run: |
          cd scripts
          mv ${{ matrix.config-file }} default_config.sh
          ./build.sh -
          cd ..
          mv scripts/ubuntu-from-scratch.iso ubuntu-${{ matrix.descriptor }}.iso          
          echo ::set-output name=TIMESTAMP::"$(date +%Y-%m-%d_%H-%M-%S)"
      - name: Compress
        run: |
          md5sum ubuntu-${{ matrix.descriptor }}.iso > ubuntu-${{ matrix.descriptor }}.md5sum
          zip ubuntu-${{ matrix.descriptor }}.zip ubuntu-${{ matrix.descriptor }}.iso ubuntu-${{ matrix.descriptor }}.md5sum
      - uses: softprops/action-gh-release@v1
        with:
          body: See Releases
          name: ISO ${{ matrix.descriptor }} Build ${{ steps.build-iso.outputs.TIMESTAMP }}
          tag_name: ${{ matrix.descriptor }}-${{ steps.build-iso.outputs.TIMESTAMP }}
          files: |
            ubuntu-${{ matrix.descriptor }}.zip
