name: build-jammy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd scripts
          sed -i -E 's/TARGET_UBUNTU_VERSION=(.*)/TARGET_UBUNTU_VERSION="jammy"/g' default_config.sh
          sed -i -E '/lupin-casper/d' chroot_build.sh
          ./build.sh -
          cd ..
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            scripts/ubuntu-from-scratch.iso
            scripts/image/md5sum.txt
